/*
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	"os"
	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/cursos-una/proyecto1-distribuidos-air-crashes/go"
)

func main() {
	log.Printf("Server started")
	sw.LoadCrashData()
	sw.LoadFlightData()
	sw.LoadStatisticData()
	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":"+os.Getenv("PORT"), router))
}
