/*
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Statistic struct {

	StatisticId string `json:"statisticId,omitempty"`

	CrashId string `json:"crashId,omitempty"`

	Aboard string `json:"aboard,omitempty"`

	Fatalities string `json:"fatalities,omitempty"`

	Ground string `json:"ground,omitempty"`
}
