/*
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TemplateId struct {

	Id string `json:"id,omitempty"`
}
