/*
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Crash struct {

	CrashId string `json:"crashId,omitempty"`

	Date string `json:"date,omitempty"`

	Time string `json:"time,omitempty"`

	Location string `json:"location,omitempty"`

	Sumary string `json:"sumary,omitempty"`
}
