/*
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Flight struct {

	FlightId string `json:"flightId,omitempty"`

	CrashId string `json:"crashId,omitempty"`

	Operator string `json:"operator,omitempty"`

	Flight string `json:"flight,omitempty"`

	Route string `json:"route,omitempty"`

	Type_ string `json:"type,omitempty"`

	Registration string `json:"registration,omitempty"`
}
