/*
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * Airplane_Crashes_and_Fatalities_Since_1908
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
 package swagger

 import (
	 "fmt"
	 "net/http"
	 "strings"
 
	 "github.com/gorilla/mux"
 )
 
 type Route struct {
	 Name        string
	 Method      string
	 Pattern     string
	 HandlerFunc http.HandlerFunc
 }
 
 type Routes []Route
 
 func NewRouter() *mux.Router {
	 router := mux.NewRouter().StrictSlash(true)
	 for _, route := range routes {
		 var handler http.Handler
		 handler = route.HandlerFunc
		 handler = Logger(handler, route.Name)
 
		 router.
			 Methods(route.Method).
			 Path(route.Pattern).
			 Name(route.Name).
			 Handler(handler)
	 }
 
	 return router
 }
 
 func Index(w http.ResponseWriter, r *http.Request) {
	 fmt.Fprintf(w, "Hello World!")
 }
 
 var routes = Routes{
	 Route{
		 "Index",
		 "GET",
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/",
		 Index,
	 },
 
	 Route{
		 "CrashCrashIdDelete",
		 strings.ToUpper("Delete"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/{crashId}",
		 CrashCrashIdDelete,
	 },
 
	 Route{
		 "CrashCrashIdFlightFlightIdDelete",
		 strings.ToUpper("Delete"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/{crashId}/flight/{flightId}",
		 CrashCrashIdFlightFlightIdDelete,
	 },
 
	 Route{
		 "CrashCrashIdFlightGet",
		 strings.ToUpper("Get"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/{crashId}/flight",
		 CrashCrashIdFlightGet,
	 },
 
	 Route{
		 "CrashCrashIdFlightPost",
		 strings.ToUpper("Post"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/{crashId}/flight",
		 CrashCrashIdFlightPost,
	 },
 
	 Route{
		 "CrashCrashIdGet",
		 strings.ToUpper("Get"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/{crashId}",
		 CrashCrashIdGet,
	 },
 
	 Route{
		 "CrashCrashIdPut",
		 strings.ToUpper("Put"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/{crashId}",
		 CrashCrashIdPut,
	 },
 
	 Route{
		 "CrashCrashIdStatisticGet",
		 strings.ToUpper("Get"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/{crashId}/statistic",
		 CrashCrashIdStatisticGet,
	 },
 
	 Route{
		 "CrashCrashIdStatisticPost",
		 strings.ToUpper("Post"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/{crashId}/statistic",
		 CrashCrashIdStatisticPost,
	 },
 
	 Route{
		 "CrashCrashIdStatisticStatisticIdDelete",
		 strings.ToUpper("Delete"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/{crashId}/statistic/{statisticId}",
		 CrashCrashIdStatisticStatisticIdDelete,
	 },
 
	 Route{
		 "CrashGet",
		 strings.ToUpper("Get"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/",
		 CrashGet,
	 },
 
	 Route{
		 "CrashPost",
		 strings.ToUpper("Post"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/crash/",
		 CrashPost,
	 },
 
	 Route{
		 "FlightFlightIdDelete",
		 strings.ToUpper("Delete"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/flight/{flightId}",
		 FlightFlightIdDelete,
	 },
 
	 Route{
		 "FlightFlightIdGet",
		 strings.ToUpper("Get"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/flight/{flightId}",
		 FlightFlightIdGet,
	 },
 
	 Route{
		 "FlightFlightIdPut",
		 strings.ToUpper("Put"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/flight/{flightId}",
		 FlightFlightIdPut,
	 },
 
	 Route{
		 "FlightGet",
		 strings.ToUpper("Get"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/flight/",
		 FlightGet,
	 },
 
	 Route{
		 "FlightPost",
		 strings.ToUpper("Post"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/flight/",
		 FlightPost,
	 },
 
	 Route{
		 "StatisticGet",
		 strings.ToUpper("Get"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/statistic/",
		 StatisticGet,
	 },
 
	 Route{
		 "StatisticPost",
		 strings.ToUpper("Post"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/statistic/",
		 StatisticPost,
	 },
 
	 Route{
		 "StatisticStatisticIdDelete",
		 strings.ToUpper("Delete"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/Statistic/{statisticId}",
		 StatisticStatisticIdDelete,
	 },
 
	 Route{
		 "StatisticStatisticIdGet",
		 strings.ToUpper("Get"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/Statistic/{statisticId}",
		 StatisticStatisticIdGet,
	 },
 
	 Route{
		 "StatisticStatisticIdPut",
		 strings.ToUpper("Put"),
		 "/1510/Airplane_Crashes_and_Fatalities_Since_1908/1.0.0/Statistic/{statisticId}",
		 StatisticStatisticIdPut,
	 },
 }
 